# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 203926a07d682c17137041d9483c59a2035fe2117c5e08a29c4f82db84dd25d14bc5675fef31c41c0f62e5d4f08062f549a556fd67b2eb8bc2422a01051b3758

test:
  secret_key_base: b4564808ed47f9ca3c31182eb076d3291a9e7e1cb8eb303cf4f1af07b618f40ea132d93609befa95da40c71c413691032ca075cf9e77479d2cdddc23800ad631

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
